services:

  samba:

    build: .

    container_name: samba

    #command: sleep infinity
    hostname: samba
    restart: unless-stopped

    #ports:
    #  - "139:1390"
    #  - "445:4450"

    volumes:
      - ./shares:/srv/samba
      - ./smb.conf:/etc/samba/smb.conf

    networks:
      - ldap-network

networks:
  ldap-network:
    external: true
