services:
  samba:
    build: .
    container_name: samba
    hostname: samba
    restart: unless-stopped

    #ports:
    #  - "445:445"
    #  - "139:139"

    volumes:
      - ./shares:/srv/samba

    networks:
      - ldap-network
      #- samba-lan
        #ipv4_address: 192.168.2.20

networks:
  #samba-lan:
  ldap-network:
    external: true
