FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y samba samba-common-bin smbclient iproute2 && \
    mkdir -p /var/log/samba /run/samba /srv/samba/public && \
    chown -R root:root /var/log/samba /run/samba /srv/samba && \
    chmod -R 755 /var/log/samba /run/samba /srv/samba && \
    rm -rf /var/lib/apt/lists/* \
    apt clean

COPY smb.conf /etc/samba/smb.conf

EXPOSE 445 139

CMD ["smbd", "--foreground", "--no-process-group"]
