services:
  samba:
    build: .
    container_name: samba
    hostname: samba
    restart: unless-stopped

    #ports:
    #  - "445:445"
    #  - "139:139"

    volumes:
      - ./shares:/srv/samba
      - ./smb.conf:/etc/samba/smb.conf:ro
      - ./nslcd.conf:/etc/nslcd.conf:ro
      - ./nsswitch.conf:/etc/nsswitch.conf:ro

    networks:
      - ldap-network

networks:
  #samba-lan:
  ldap-network:
    external: true
    

