[libdefaults]
 default_realm = ALPESNET.LOCAL
 dns_lookup_kdc = false

[realms]

 ALPESNET.LOCAL = {
     kdc = kerberos
     admin_server = kerberos
 }

[domain_realm]

 .alpesnet.local = ALPESNET.LOCAL
 alpesnet.local = ALPESNET.LOCAL
