[global]

   workgroup = ALPESNET

   security = user

   passdb backend = ldapsam:ldap://ldap

   ldap admin dn = cn=admin,dc=alpesnet,dc=local

   ldap suffix = dc=alpesnet,dc=local

   ldap user suffix = ou=People

   ldap group suffix = ou=Groups

   ldap machine suffix = ou=Computers

   ldap passwd sync = yes

   ldap ssl = off

[Public]

   path = /srv/samba/public

   writable = yes

   browseable = yes

   guest ok = no
