[global]

   workgroup = ALPESNET

   security = user

   passdb backend = ldapsam:ldap://openldap:3890

   ldap admin dn = cn=admin,dc=AlpesNet,dc=local

   ldap suffix = dc=AlpesNet,dc=local

   ldap user suffix = ou=people

   ldap group suffix = ou=group

   ldap machine suffix = ou=computers

   ldap passwd sync = yes

   ldap ssl = off

[Public]

   path = /srv/samba/public

   writable = yes

   browseable = yes

   guest ok = no
